name: Build SDK

on:
  push:
    branches: [ webos-sdk ]

jobs:
  load-config:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Initialize config
        run: make webos_tv_defconfig

  build-toolchain:
    needs: load-config
    runs-on: ubuntu-latest

    steps:
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            dl
            output
          key: ${{ runner.os }}-toolchain-cache-1

      - name: Build Toolchain
        run: make toolchain

  build-sdk:
    needs: build-toolchain
    runs-on: ubuntu-latest

    steps:
      - name: Build SDK
        run: make sdk